# from django.core.exceptions import ValidationError


class RegionValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class DistrictValidator:
    def __init__(self): ...

    def __call__(self):
        return True
