# from django.core.exceptions import ValidationError


class ProductValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class TagValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class CategoryValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class ColorValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class SizeValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class BasketValidator:
    def __init__(self): ...

    def __call__(self):
        return True
